// <auto-generated />
using Above_backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Above_backend.Migrations
{
    [DbContext(typeof(AboveDBContext))]
    [Migration("20250303112650_NamingCorrection")]
    partial class NamingCorrection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Above_backend.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Armor_prof")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hit_Dice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellCaster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Starting_gold")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tool_prof")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Weapon_prof")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Above_backend.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attunement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Consumable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfReq")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Above_backend.Models.Features", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Armor_prof")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelReq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginSubClassId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Saving_throws")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tool_prof")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Weapon_prof")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.HasIndex("OriginEquipmentId");

                    b.HasIndex("OriginRaceId");

                    b.HasIndex("OriginSubClassId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Above_backend.Models.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Above_backend.Models.Spells", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComponentPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Concentration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginSubClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.HasIndex("OriginEquipmentId");

                    b.HasIndex("OriginRaceId");

                    b.HasIndex("OriginSubClassId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Above_backend.Models.SubClasses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.ToTable("SubClasses");
                });

            modelBuilder.Entity("Above_backend.Models.Features", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "OriginClass")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.HasOne("Above_backend.Models.Equipment", "OriginEquipment")
                        .WithMany()
                        .HasForeignKey("OriginEquipmentId");

                    b.HasOne("Above_backend.Models.Races", "OriginRace")
                        .WithMany()
                        .HasForeignKey("OriginRaceId");

                    b.HasOne("Above_backend.Models.SubClasses", "OriginSubClass")
                        .WithMany()
                        .HasForeignKey("OriginSubClassId");

                    b.Navigation("OriginClass");

                    b.Navigation("OriginEquipment");

                    b.Navigation("OriginRace");

                    b.Navigation("OriginSubClass");
                });

            modelBuilder.Entity("Above_backend.Models.Spells", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "OriginClass")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.HasOne("Above_backend.Models.Equipment", "OriginEquipment")
                        .WithMany()
                        .HasForeignKey("OriginEquipmentId");

                    b.HasOne("Above_backend.Models.Races", "OriginRace")
                        .WithMany()
                        .HasForeignKey("OriginRaceId");

                    b.HasOne("Above_backend.Models.SubClasses", "OriginSubClass")
                        .WithMany()
                        .HasForeignKey("OriginSubClassId");

                    b.Navigation("OriginClass");

                    b.Navigation("OriginEquipment");

                    b.Navigation("OriginRace");

                    b.Navigation("OriginSubClass");
                });

            modelBuilder.Entity("Above_backend.Models.SubClasses", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "OriginClass")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.Navigation("OriginClass");
                });
#pragma warning restore 612, 618
        }
    }
}
