// <auto-generated />
using Above_backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Above_backend.Migrations
{
    [DbContext(typeof(AboveDBContext))]
    [Migration("20250224105846_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Above_backend.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Armor_prof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hit_Dice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpellCaster")
                        .HasColumnType("int");

                    b.Property<int>("Starting_gold")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Tool_prof")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Weapon_prof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Above_backend.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AC")
                        .HasColumnType("int");

                    b.Property<int>("Attunement")
                        .HasColumnType("int");

                    b.Property<int>("Consumable")
                        .HasColumnType("int");

                    b.Property<string>("DamageDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ProfReq")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Above_backend.Models.Features", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Armor_prof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelReq")
                        .HasColumnType("int");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginRaceId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginSubClassId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Saving_throws")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Tool_prof")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Weapon_prof")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.HasIndex("OriginEquipmentId");

                    b.HasIndex("OriginRaceId");

                    b.HasIndex("OriginSubClassId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Above_backend.Models.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Above_backend.Models.Spells", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComponentPrice")
                        .HasColumnType("int");

                    b.Property<int>("Concentration")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginRaceId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginSubClassId")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("Ritual")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.HasIndex("OriginEquipmentId");

                    b.HasIndex("OriginRaceId");

                    b.HasIndex("OriginSubClassId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Above_backend.Models.SubClasses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubClasses");
                });

            modelBuilder.Entity("Above_backend.Models.Features", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "Classes")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.HasOne("Above_backend.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("OriginEquipmentId");

                    b.HasOne("Above_backend.Models.Races", "Races")
                        .WithMany()
                        .HasForeignKey("OriginRaceId");

                    b.HasOne("Above_backend.Models.SubClasses", "SubClasses")
                        .WithMany()
                        .HasForeignKey("OriginSubClassId");

                    b.Navigation("Classes");

                    b.Navigation("Equipment");

                    b.Navigation("Races");

                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("Above_backend.Models.Spells", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "Classes")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.HasOne("Above_backend.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("OriginEquipmentId");

                    b.HasOne("Above_backend.Models.Races", "Races")
                        .WithMany()
                        .HasForeignKey("OriginRaceId");

                    b.HasOne("Above_backend.Models.SubClasses", "SubClasses")
                        .WithMany()
                        .HasForeignKey("OriginSubClassId");

                    b.Navigation("Classes");

                    b.Navigation("Equipment");

                    b.Navigation("Races");

                    b.Navigation("SubClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
