// <auto-generated />
using System;
using Above_backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Above_backend.Migrations
{
    [DbContext(typeof(AboveDBContext))]
    partial class AboveDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Above_backend.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ArmorProf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HalfCaster")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SavingThrows")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellCaster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingGold")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ToolProf")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("WeaponProf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Above_backend.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attunement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Consumable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDie")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfReq")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Above_backend.Models.Features", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ArmorProf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelReq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginSubClassId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("SavingThrows")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SkillProf")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ToolProf")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("WeaponProf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.HasIndex("OriginEquipmentId");

                    b.HasIndex("OriginRaceId");

                    b.HasIndex("OriginSubClassId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Above_backend.Models.FeaturesToFeaturesConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubFeatureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginFeatureId");

                    b.HasIndex("SubFeatureId");

                    b.ToTable("FeaturesToFeaturesConnections");
                });

            modelBuilder.Entity("Above_backend.Models.Races", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Above_backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Above_backend.Models.Saves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sheet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("Above_backend.Models.Spells", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComponentPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Concentration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LearnedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginEquipmentId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Above_backend.Models.SubClasses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginClassId");

                    b.ToTable("SubClasses");
                });

            modelBuilder.Entity("Above_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Above_backend.Models.Features", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "Classes")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.HasOne("Above_backend.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("OriginEquipmentId");

                    b.HasOne("Above_backend.Models.Races", "Races")
                        .WithMany()
                        .HasForeignKey("OriginRaceId");

                    b.HasOne("Above_backend.Models.SubClasses", "SubClasses")
                        .WithMany()
                        .HasForeignKey("OriginSubClassId");

                    b.Navigation("Classes");

                    b.Navigation("Equipment");

                    b.Navigation("Races");

                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("Above_backend.Models.FeaturesToFeaturesConnection", b =>
                {
                    b.HasOne("Above_backend.Models.Features", "OriginFeature")
                        .WithMany()
                        .HasForeignKey("OriginFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Above_backend.Models.Features", "SubFeature")
                        .WithMany()
                        .HasForeignKey("SubFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginFeature");

                    b.Navigation("SubFeature");
                });

            modelBuilder.Entity("Above_backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Above_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Above_backend.Models.Saves", b =>
                {
                    b.HasOne("Above_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Above_backend.Models.Spells", b =>
                {
                    b.HasOne("Above_backend.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("OriginEquipmentId");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Above_backend.Models.SubClasses", b =>
                {
                    b.HasOne("Above_backend.Models.Classes", "Classes")
                        .WithMany()
                        .HasForeignKey("OriginClassId");

                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
